# 🚀 NumPy Exercises XP - Week 5 Day 1

**Learning Objectives:**
- Mastering core NumPy operations including array creation, manipulation, and basic operations
- Developing skills in handling one-dimensional and multi-dimensional arrays
- Building proficiency with NumPy's powerful array manipulation capabilities

**Date:** October 27th, 2025

In [8]:
import numpy as np

print(" NumPy imported successfully!")
print(f"NumPy version: {np.__version__}")

 NumPy imported successfully!
NumPy version: 2.3.3


##  Exercise 1: Array Creation and Manipulation


In [9]:
array_1d = np.arange(10)

print("Exercise 1 - Creating 1D array from 0 to 9:")
print(array_1d)
print(f"Array shape: {array_1d.shape}")
print(f"Array type: {type(array_1d)}")

Exercise 1 - Creating 1D array from 0 to 9:
[0 1 2 3 4 5 6 7 8 9]
Array shape: (10,)
Array type: <class 'numpy.ndarray'>


##  Exercise 2: Type Conversion and Array Operations


In [10]:
original_list = [3.14, 2.17, 0, 1, 2]
float_array = np.array(original_list)
int_array = float_array.astype(int)

print("Exercise 2 - Type conversion:")
print(f"Original list: {original_list}")
print(f"Float array: {float_array}")
print(f"Integer array: {int_array}")
print(f"Original dtype: {float_array.dtype}")
print(f"Converted dtype: {int_array.dtype}")

Exercise 2 - Type conversion:
Original list: [3.14, 2.17, 0, 1, 2]
Float array: [3.14 2.17 0.   1.   2.  ]
Integer array: [3 2 0 1 2]
Original dtype: float64
Converted dtype: int64


##  Exercise 3: Working with Multi-Dimensional Arrays


In [11]:
# Creating 3x3 array with values from 1 to 9 using arange and reshape
array_3x3 = np.arange(1, 10).reshape(3, 3)

print("Exercise 3 - Creating 3x3 array:")
print(array_3x3)
print(f"Array shape: {array_3x3.shape}")
print(f"Array dimensions: {array_3x3.ndim}")
print(f"Total elements: {array_3x3.size}")

Exercise 3 - Creating 3x3 array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array shape: (3, 3)
Array dimensions: 2
Total elements: 9


##  Exercise 4: Creating Multi-Dimensional Array with Random Numbers


In [12]:
np.random.seed(42)

# Creating 4x5 array with random numbers between 0 and 1
random_array = np.random.rand(4, 5)

print("Exercise 4 - Creating 4x5 random array:")
print(random_array)
print(f"Array shape: {random_array.shape}")
print(f"Min value: {random_array.min():.4f}")
print(f"Max value: {random_array.max():.4f}")

Exercise 4 - Creating 4x5 random array:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]]
Array shape: (4, 5)
Min value: 0.0206
Max value: 0.9699


##  Exercise 5: Indexing Arrays


In [13]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

# Selecting the second row (index 1)
second_row = array[1]

print("Exercise 5 - Indexing arrays:")
print("Original array:")
print(array)
print(f"\nSecond row (index 1): {second_row}")
print(f"Shape of second row: {second_row.shape}")
print(f"Type of second row: {type(second_row)}")

Exercise 5 - Indexing arrays:
Original array:
[[21 22 23 22 22]
 [20 21 22 23 24]
 [21 22 23 22 22]]

Second row (index 1): [20 21 22 23 24]
Shape of second row: (5,)
Type of second row: <class 'numpy.ndarray'>


##  Exercise 6: Reversing Elements


In [14]:
# Creating array from 0 to 9 and reversing it
original_array = np.arange(10)
reversed_array = original_array[::-1]

print("Exercise 6 - Reversing elements:")
print(f"Original array: {original_array}")
print(f"Reversed array: {reversed_array}")

# Alternative methods for reversing
reversed_with_flip = np.flip(original_array)
print(f"Using np.flip(): {reversed_with_flip}")

Exercise 6 - Reversing elements:
Original array: [0 1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1 0]
Using np.flip(): [9 8 7 6 5 4 3 2 1 0]


##  Exercise 7: Identity Matrix


In [15]:
# Creating 4x4 identity matrix
identity_matrix = np.eye(4)

print("Exercise 7 - Creating 4x4 identity matrix:")
print(identity_matrix)
print(f"Matrix shape: {identity_matrix.shape}")
print(f"Data type: {identity_matrix.dtype}")

# Alternative method using identity function
identity_alt = np.identity(4)
print(f"\nUsing np.identity(): Same result: {np.array_equal(identity_matrix, identity_alt)}")

Exercise 7 - Creating 4x4 identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matrix shape: (4, 4)
Data type: float64

Using np.identity(): Same result: True


##  Exercise 8: Simple Aggregate Functions


In [16]:
# Creating array from 0 to 9 for sum and average calculation
numbers_array = np.arange(10)

# Calculating sum and average
array_sum = np.sum(numbers_array)
array_average = np.mean(numbers_array)

print("Exercise 8 - Simple aggregate functions:")
print(f"Array: {numbers_array}")
print(f"Sum: {array_sum}, Average: {array_average}")

# Additional statistics
print(f"Median: {np.median(numbers_array)}")
print(f"Standard deviation: {np.std(numbers_array):.2f}")
print(f"Min: {np.min(numbers_array)}, Max: {np.max(numbers_array)}")

Exercise 8 - Simple aggregate functions:
Array: [0 1 2 3 4 5 6 7 8 9]
Sum: 45, Average: 4.5
Median: 4.5
Standard deviation: 2.87
Min: 0, Max: 9


##  Exercise 9: Create Array and Change its Structure


In [17]:
# Creating array from 1 to 20 and reshaping to 4x5 matrix
linear_array = np.arange(1, 21)
matrix_4x5 = linear_array.reshape(4, 5)

print("Exercise 9 - Creating and reshaping array:")
print(f"Original 1D array: {linear_array}")
print(f"\nReshaped 4x5 matrix:")
print(matrix_4x5)
print(f"Original shape: {linear_array.shape}")
print(f"New shape: {matrix_4x5.shape}")
print(f"Total elements: {matrix_4x5.size}")

Exercise 9 - Creating and reshaping array:
Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Reshaped 4x5 matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Original shape: (20,)
New shape: (4, 5)
Total elements: 20


##  Exercise 10: Conditional Selection of Values


In [18]:
# Creating array from 0 to 9 and extracting odd numbers
source_array = np.arange(10)
odd_numbers = source_array[source_array % 2 == 1]

print("Exercise 10 - Conditional selection:")
print(f"Original array: {source_array}")
print(f"Odd numbers: {odd_numbers}")

# Alternative approach using where function
odd_with_where = np.where(source_array % 2 == 1, source_array, -1)
odd_filtered = odd_with_where[odd_with_where != -1]
print(f"Using np.where: {odd_filtered}")

even_numbers = source_array[source_array % 2 == 0]
greater_than_5 = source_array[source_array > 5]
print(f"Even numbers: {even_numbers}")
print(f"Numbers > 5: {greater_than_5}")

Exercise 10 - Conditional selection:
Original array: [0 1 2 3 4 5 6 7 8 9]
Odd numbers: [1 3 5 7 9]
Using np.where: [1 3 5 7 9]
Even numbers: [0 2 4 6 8]
Numbers > 5: [6 7 8 9]
