In [1]:
import numpy as np

print("NumPy imported successfully!")
print(f"NumPy version: {np.__version__}")

NumPy imported successfully!
NumPy version: 2.3.3


## Exercise 1: Minimum and Maximum of Random Array

In [2]:
np.random.seed(42)  
random_array = np.random.rand(5, 5)

# Finding minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print("Exercise 1 - Random 5x5 array:")
print(random_array)
print(f"\nMin: {min_value:.2f}, Max: {max_value:.2f}")

print(f"Mean: {random_array.mean():.2f}")
print(f"Standard deviation: {random_array.std():.2f}")

Exercise 1 - Random 5x5 array:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]

Min: 0.02, Max: 0.97
Mean: 0.44
Standard deviation: 0.28


## Exercise 2: Matrix Normalization

In [3]:
#  3x3 random matrix for normalization
random_matrix = np.random.rand(3, 3)

# Calculating mean and standard deviation
matrix_mean = random_matrix.mean()
matrix_std = random_matrix.std()

# Normalizing the matrix
normalized_matrix = (random_matrix - matrix_mean) / matrix_std

print("Exercise 2 - Matrix Normalization:")
print("Original matrix:")
print(random_matrix)
print(f"\nMean: {matrix_mean:.4f}")
print(f"Standard deviation: {matrix_std:.4f}")
print("\nNormalized matrix:")
print(normalized_matrix)

# Verifying normalization (mean should be ~0, std should be ~1)
print(f"\nNormalized mean: {normalized_matrix.mean():.6f}")
print(f"Normalized std: {normalized_matrix.std():.6f}")

Exercise 2 - Matrix Normalization:
Original matrix:
[[0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485]
 [0.17052412 0.06505159 0.94888554]]

Mean: 0.4367
Standard deviation: 0.3092

Normalized matrix:
[[ 1.12700254 -0.76635596  0.25084964]
 [ 0.50366341 -1.26183963  0.55259073]
 [-0.86061821 -1.20168835  1.65639582]]

Normalized mean: 0.000000
Normalized std: 1.000000


## Exercise 3: Evenly Spaced Elements in Array

In [4]:
# Creating 50 evenly spaced elements between 0 and 10 
evenly_spaced = np.linspace(0, 10, 50)

print("Exercise 3 - Evenly spaced elements:")
print(f"First 10 elements: {evenly_spaced[:10]}")
print(f"Last 10 elements: {evenly_spaced[-10:]}")
print(f"\nFull array:")
print(evenly_spaced)
print(f"\nArray length: {len(evenly_spaced)}")
print(f"Step size: {evenly_spaced[1] - evenly_spaced[0]:.4f}")

# Alternative using arange for exclusive endpoint
evenly_spaced_exclusive = np.arange(0, 10, 10/50)
print(f"\nUsing arange (exclusive): {evenly_spaced_exclusive[:5]}...{evenly_spaced_exclusive[-5:]}")

Exercise 3 - Evenly spaced elements:
First 10 elements: [0.         0.20408163 0.40816327 0.6122449  0.81632653 1.02040816
 1.2244898  1.42857143 1.63265306 1.83673469]
Last 10 elements: [ 8.16326531  8.36734694  8.57142857  8.7755102   8.97959184  9.18367347
  9.3877551   9.59183673  9.79591837 10.        ]

Full array:
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]

Array length: 50
Step size: 0.2041

Using arange (exclusive): [0. 

## Exercise 4: Matrix Multiplication

In [5]:
# Creating compatible matrices for multiplication
matrix_5x3 = np.random.rand(5, 3)
matrix_3x2 = np.random.rand(3, 2)

# Performing matrix multiplication using @ operator
result_matrix = matrix_5x3 @ matrix_3x2

print("Exercise 4 - Matrix Multiplication:")
print("Matrix A (5x3):")
print(matrix_5x3)
print("\nMatrix B (3x2):")
print(matrix_3x2)
print("\nResult (5x2):")
print(result_matrix)

print(f"\nMatrix A shape: {matrix_5x3.shape}")
print(f"Matrix B shape: {matrix_3x2.shape}")
print(f"Result shape: {result_matrix.shape}")

# Alternative using np.dot()
result_dot = np.dot(matrix_5x3, matrix_3x2)
print(f"\nUsing np.dot() gives same result: {np.array_equal(result_matrix, result_dot)}")

Exercise 4 - Matrix Multiplication:
Matrix A (5x3):
[[0.96563203 0.80839735 0.30461377]
 [0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852]
 [0.9093204  0.25877998 0.66252228]
 [0.31171108 0.52006802 0.54671028]]

Matrix B (3x2):
[[0.18485446 0.96958463]
 [0.77513282 0.93949894]
 [0.89482735 0.59789998]]

Result (5x2):
[[1.07769343 1.87787899]
 [0.94228709 1.00070475]
 [0.43715898 0.60410548]
 [0.96152385 1.52090866]
 [0.94995429 1.11771169]]

Matrix A shape: (5, 3)
Matrix B shape: (3, 2)
Result shape: (5, 2)

Using np.dot() gives same result: True


## Exercise 5: Advanced Matrix Multiplication

In [6]:
# Creating two matrices with compatible dimensions for multiplication
# Matrix A: 4x3, Matrix B: 3x5 -> Result: 4x5
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])

matrix_B = np.array([[2, 1, 0, 3, 1],
                     [1, 2, 1, 0, 2],
                     [0, 1, 2, 1, 0]])

# Performing matrix multiplication
multiplication_result = matrix_A @ matrix_B

print("Exercise 5 - Advanced Matrix Multiplication:")
print("Matrix A (4x3):")
print(matrix_A)
print("\nMatrix B (3x5):")
print(matrix_B)
print("\nMultiplication Result (4x5):")
print(multiplication_result)

# Demonstrating different compatible matrix combinations
print("\nDemonstrating matrix multiplication rules:")

# Example 1: 2x4 @ 4x3 = 2x3
example_A = np.random.rand(2, 4)
example_B = np.random.rand(4, 3)
example_result = example_A @ example_B
print(f"Example 1: {example_A.shape} @ {example_B.shape} = {example_result.shape}")

# Example 2: 3x1 @ 1x3 = 3x3 (outer product)
vector_col = np.array([[1], [2], [3]])
vector_row = np.array([[4, 5, 6]])
outer_product = vector_col @ vector_row
print(f"Example 2: {vector_col.shape} @ {vector_row.shape} = {outer_product.shape}")
print("Outer product result:")
print(outer_product)

Exercise 5 - Advanced Matrix Multiplication:
Matrix A (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Matrix B (3x5):
[[2 1 0 3 1]
 [1 2 1 0 2]
 [0 1 2 1 0]]

Multiplication Result (4x5):
[[ 4  8  8  6  5]
 [13 20 17 18 14]
 [22 32 26 30 23]
 [31 44 35 42 32]]

Demonstrating matrix multiplication rules:
Example 1: (2, 4) @ (4, 3) = (2, 3)
Example 2: (3, 1) @ (1, 3) = (3, 3)
Outer product result:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
