# NumPy Exercises XP Ninja - Week 5 Day 1



In [1]:
import numpy as np

print("NumPy imported successfully!")
print(f"NumPy version: {np.__version__}")

NumPy imported successfully!
NumPy version: 2.3.3


## Exercise 1: Maximum Value Replacement in Matrix

In [2]:
# Creating random 5x5 matrix and replacing maximum value with 0
np.random.seed(42)
matrix = np.random.rand(5, 5)

print("Exercise 1 - Original matrix:")
print(matrix)

# Finding position of maximum value
max_position = np.unravel_index(np.argmax(matrix), matrix.shape)
max_value = matrix.max()

print(f"\nMaximum value: {max_value:.4f} at position {max_position}")

# Replacing maximum value with 0
matrix[max_position] = 0

print("\nMatrix after replacing maximum value with 0:")
print(matrix)

# Alternative method using argmax
matrix_copy = np.random.rand(5, 5)
flat_index = np.argmax(matrix_copy)
matrix_copy.flat[flat_index] = 0
print(f"\nAlternative method result (different random matrix):")
print(matrix_copy)

Exercise 1 - Original matrix:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]

Maximum value: 0.9699 at position (np.int64(2), np.int64(1))

Matrix after replacing maximum value with 0:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.         0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]

Alternative method result (different random matrix):
[[0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.        ]
 [0.80839735 0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.2587

## Exercise 2: Finding Common Values in Arrays

In [3]:
array1 = np.array([0.1, 0.35, 0.66, 0.8, 0.76])
array2 = np.array([0.35, 0.9, 0.66, 0.3, 0.76])

print("Exercise 2 - Finding common values:")
print(f"Array 1: {array1}")
print(f"Array 2: {array2}")

# Finding common values using intersect1d
common_values = np.intersect1d(array1, array2)
print(f"Common values: {common_values}")

# Alternative method using in1d
mask = np.in1d(array1, array2)
common_alt = array1[mask]
print(f"Common values (alternative): {common_alt}")

# Example with random arrays (might not have common exact values)
random_array1 = np.random.rand(5)
random_array2 = np.random.rand(5)
random_common = np.intersect1d(random_array1, random_array2)

print(f"\nRandom array 1: {random_array1}")
print(f"Random array 2: {random_array2}")
print(f"Common values in random arrays: {random_common}")
print(f"Number of common values: {len(random_common)}")

Exercise 2 - Finding common values:
Array 1: [0.1  0.35 0.66 0.8  0.76]
Array 2: [0.35 0.9  0.66 0.3  0.76]
Common values: [0.35 0.66 0.76]
Common values (alternative): [0.35 0.66 0.76]

Random array 1: [0.96958463 0.77513282 0.93949894 0.89482735 0.59789998]
Random array 2: [0.92187424 0.0884925  0.19598286 0.04522729 0.32533033]
Common values in random arrays: []
Number of common values: 0


C:\Users\PC\AppData\Local\Temp\ipykernel_8164\3284708524.py:13: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  mask = np.in1d(array1, array2)


## Exercise 3: Sorting Array in Ascending and Descending Order

In [4]:
# Creating random 1D array of size 10 and sorting it
random_array = np.random.rand(10)

print("Exercise 3 - Sorting arrays:")
print(f"Original array: {random_array}")

# Sorting in ascending order
ascending = np.sort(random_array)
print(f"Ascending: {ascending}")

# Sorting in descending order
descending = np.sort(random_array)[::-1]
print(f"Descending: {descending}")

# Alternative method for descending using negative sorting
descending_alt = -np.sort(-random_array)
print(f"Descending (alternative): {descending_alt}")

# Using argsort to get indices
ascending_indices = np.argsort(random_array)
descending_indices = np.argsort(random_array)[::-1]

print(f"\nAscending indices: {ascending_indices}")
print(f"Descending indices: {descending_indices}")

# Demonstrating with specific values
demo_array = np.array([0.5, 0.1, 0.9, 0.3, 0.7, 0.2, 0.8, 0.4, 0.6, 1.0])
print(f"\nDemo array: {demo_array}")
print(f"Ascending: {np.sort(demo_array)}")
print(f"Descending: {np.sort(demo_array)[::-1]}")

Exercise 3 - Sorting arrays:
Original array: [0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
 0.14092422 0.80219698 0.07455064 0.98688694]
Ascending: [0.07455064 0.14092422 0.27134903 0.28093451 0.35675333 0.38867729
 0.54269608 0.80219698 0.82873751 0.98688694]
Descending: [0.98688694 0.82873751 0.80219698 0.54269608 0.38867729 0.35675333
 0.28093451 0.27134903 0.14092422 0.07455064]
Descending (alternative): [0.98688694 0.82873751 0.80219698 0.54269608 0.38867729 0.35675333
 0.28093451 0.27134903 0.14092422 0.07455064]

Ascending indices: [8 6 1 4 3 0 5 7 2 9]
Descending indices: [9 2 7 5 0 3 4 1 6 8]

Demo array: [0.5 0.1 0.9 0.3 0.7 0.2 0.8 0.4 0.6 1. ]
Ascending: [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
Descending: [1.  0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1]


## Exercise 4: Matrix Rank Determination

In [5]:
# Generating random 4x4 matrix and finding its rank
random_matrix = np.random.rand(4, 4)

print("Exercise 4 - Matrix rank determination:")
print("Random 4x4 matrix:")
print(random_matrix)

# Calculating matrix rank using numpy.linalg.matrix_rank
matrix_rank = np.linalg.matrix_rank(random_matrix)
print(f"\nRank: {matrix_rank}")

# Demonstrating different rank scenarios
print("\nDemonstrating different rank scenarios:")

# Full rank matrix (rank = 4)
full_rank_matrix = np.eye(4) + np.random.rand(4, 4) * 0.1
full_rank = np.linalg.matrix_rank(full_rank_matrix)
print(f"Full rank matrix rank: {full_rank}")

# Rank deficient matrix (rank < 4)
rank_deficient = np.array([[1, 2, 3, 4],
                          [2, 4, 6, 8],  # This row is 2x first row
                          [5, 6, 7, 8],
                          [9, 10, 11, 12]])
deficient_rank = np.linalg.matrix_rank(rank_deficient)
print(f"Rank deficient matrix rank: {deficient_rank}")

# Zero matrix (rank = 0)
zero_matrix = np.zeros((4, 4))
zero_rank = np.linalg.matrix_rank(zero_matrix)
print(f"Zero matrix rank: {zero_rank}")

# Understanding rank through singular values
U, s, Vt = np.linalg.svd(random_matrix)
print(f"\nSingular values: {s}")
print(f"Number of non-zero singular values: {np.sum(s > 1e-10)}")

Exercise 4 - Matrix rank determination:
Random 4x4 matrix:
[[0.77224477 0.19871568 0.00552212 0.81546143]
 [0.70685734 0.72900717 0.77127035 0.07404465]
 [0.35846573 0.11586906 0.86310343 0.62329813]
 [0.33089802 0.06355835 0.31098232 0.32518332]]

Rank: 4

Demonstrating different rank scenarios:
Full rank matrix rank: 4
Rank deficient matrix rank: 2
Zero matrix rank: 0

Singular values: [1.86148887 0.83790156 0.59384841 0.061482  ]
Number of non-zero singular values: 4


## Exercise 5: Creating Border Array

In [6]:
# Creating 2D array with 1 on border and 0 inside
size = 5
border_array = np.zeros((size, size), dtype=int)

# Setting border elements to 1
border_array[0, :] = 1  # Top row
border_array[-1, :] = 1  # Bottom row
border_array[:, 0] = 1  # Left column
border_array[:, -1] = 1  # Right column

print("Exercise 5 - Creating border array:")
print(border_array)

# Alternative method using ones and slicing
def create_border_array(n):
    arr = np.ones((n, n), dtype=int)
    arr[1:-1, 1:-1] = 0
    return arr

alternative_border = create_border_array(5)
print("\nAlternative method:")
print(alternative_border)

# Creating different sizes
print("\nDifferent sizes:")
for size in [3, 4, 6, 7]:
    border = create_border_array(size)
    print(f"\n{size}x{size} border array:")
    print(border)

# Method using pad function
center = np.zeros((3, 3), dtype=int)
padded_border = np.pad(center, 1, mode='constant', constant_values=1)
print(f"\nUsing np.pad method:")
print(padded_border)

Exercise 5 - Creating border array:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

Alternative method:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

Different sizes:

3x3 border array:
[[1 1 1]
 [1 0 1]
 [1 1 1]]

4x4 border array:
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]

6x6 border array:
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]

7x7 border array:
[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]

Using np.pad method:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
